### ISSUE TITLE
Project 1 share thread

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring21#13]
Hi everyone,

I wanted to start a thread where you all could share your Project 1's.

In reply to this thread, please share the following:

+ The link to your P1 on production (so everyone can view it)
+ The link to your P1 on Github (so we can see the code behind it)
+ A note (or more) about your experience building the project. Example:
   + Was there some part you got stuck on? If so, how did you get past the issue?
   + Did you use a technique, function, etc. that was unique from what we saw in lecture?
   + Did you execute an additional, unique string processor? If so describe.
   + Etc.

**Comment by susanBuck** [comment]
Related to this, I also wanted to share the underlying code to the p1 example, in case you want to compare/contrast the code with your own - specifically the approach to the string processor functions:

+ <https://github.com/susanBuck/e15p1>
+ <https://github.com/susanBuck/e15p1/blob/master/process.php>

**Comment by adejeffchen** [comment]
- [http://e15p1.adejeffchen.me/](http://e15p1.adejeffchen.me/)
- [https://github.com/adejeffchen/e15/tree/main/p1](https://github.com/adejeffchen/e15/tree/main/p1)
- for isPalindrome, I wrote a helper function that removes special characters, numeric characters, and spaces with str_replace. Not sure if there is a better way to do this. 

```
function removeNonAlphabetic($aWord)
{
    return str_replace(array("~", "`", "!", "@", "#", "$", "%", "^",
    "&", "*", "(", ")", "-", "_", "+", "=", "[", "{", "]", "}",
    "\\", ";", ":", "'", "\"", ",", "<", ".", ">", "/", "?",
    "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", " "), '', $aWord);
}
```

**Comment by kristysunnyd** [comment]
Hi everyone! 

Here are the links for my Project 1:
- http://e15p1.sunnykreme.me/
- https://github.com/kristysunnyd/e15/tree/main/p1
- For isPalindrome, I struggled a little with how to ignore non-alphabetical characters in the string, so I had a little help from [stackoverflow](https://stackoverflow.com/questions/659025/how-to-remove-non-alphanumeric-characters): `preg_replace('/[^a-z\d ]/i', '', $str);`

    - With this I also learned the use of the function `preg_replace()` -> [documentation here](https://www.php.net/manual/en/function.preg-replace.php)
- Overall, I found this project manageable and fun to build. 😄

**Comment by kerynegan** [comment]
Hi everyone - 

Here are my links:

- [http://e15p1.kerynegan.me/](http://e15p1.kerynegan.me/)
- [https://github.com/kerynegan/e15/blob/main/p1/process.php](https://github.com/kerynegan/e15/blob/main/p1/process.php)

- For isPalindrome, I also struggled for a long while, but ultimately ended up with `preg_replace('%\W%',"", $inputString);` [based on this reference](https://www.php.net/manual/en/regexp.reference.escape.php), which I was really happy with. 
- For shiftLetters, I was really happy with my solution using ord() and chr(). It looks like you went the same route, @adejeffchen - glad to be in good company!
- I'm seeing from Susan's and others' solutions here that I might want to think about ways to tighten my code. I think I tend to be very 'step-by-step,' but I clearly could have combined some functions (strtolower() inside of the preg_replace() instead of two separate steps! Something to think about, I guess. 🙂 

As an aside, I'd love to do a deeper dive into those escape sequences if you have any friendly references for them, @susanBuck! It feels like a part of php I haven't entirely wrapped my head around yet.

**Comment by susanBuck** [comment]
@kerynegan -

Regular expressions are something I think no developer ever truly wraps their head around 😄. They're used in a lot of languages beyond PHP, though, so it's definitely a useful skill to have.

Some of my favorite tools/ref's for working with regexps:
+ https://regexr.com
+ http://phpliveregex.com

My approach to writing regexps is to search for some existing expression that does something close to what I want, then studying it and tinker with it until it does what I want. Tools like the above linked ones are really helpful for this.

**Comment by karnaout** [comment]
Here are my links: 
-  [http://e15p1.khaledarnaout.me/](http://e15p1.khaledarnaout.me/)

- [https://github.com/karnaout/e15/tree/main/p1](https://github.com/karnaout/e15/tree/main/p1)
- Overall the project looked very straightforward and I kinda enjoyed it. I thought it was a very good exercise to get comfortable and used Laravel and PHP.
