### ISSUE TITLE
Laravel redirects to a route but then apache gives 404 error

### ISSUE THREAD

**Issue by adejeffchen** [susanBuck/e15-spring21#17]
**Environment**
Production server / DigitalOcean

**What operating system are you using?**
Mac

**Describe the problem**
The application form redirect works locally. However, after I followed the [prep steps](https://hesweb.dev/e15/notes/laravel/prep-digital-ocean-for-laravel) and deployed the app to [http://e15p2.adejeffchen.me/](http://e15p2.adejeffchen.me/), the form redirect gives me 404. 
The homepage displays fine but when I submit the form, the POST status code is 404 Not Found. 

**Steps taken**
Re-run Module rewrite by running
```
root@lamp-ubuntu-s-1vcpu-1gb-sfo2-01:/var/www/html/e15/p2# sudo a2enmod rewrite
Module rewrite already enabled
```

Double-checked VirtualHost
```
<VirtualHost *:80>
    ServerName e15p2.adejeffchen.me
    DocumentRoot "/var/www/html/e15/p2/public"
    <Directory "/var/www/html/e15/p1/public">
        AllowOverride All
        Options -Indexes
        Require all granted
    </Directory>
</VirtualHost>
```

Thanks.

**Comment by susanBuck** [comment]
Hi @adejeffchen -

Looks like you've set everything up correctly. Typically this issue is caused by modrewrite not being enabled, but you confirm that's not the case.

I can log into your server and do some troubleshooting to see if I can narrow down the problem. If this is okay with you, you can give me server access following these instructions: https://hesweb.dev/e15/notes/appendix/instructor-server-access

**Comment by adejeffchen** [comment]
Thank you @susanBuck. I have added your public key to my server. 

Thanks!

**Comment by susanBuck** [comment]
@adejeffchen - Confirming I was able to log in. Poking around now and will report back on what I find.

**Comment by susanBuck** [comment]
Just spotted the problem - in your VirtualHost, _DocumentRoot_ is correctly pointing to `/var/www/html/e15/p2/public`, but _Directory_ is pointing to `/var/www/html/e15/p1/public` (should be p2, not p1).

The reason this was causing the URL routing/rewriting to fail is because the setting of _AllowOverride All_ was not applying to the directory, and without that, the `.htaccess` file in charge of the rewriting wasn't being read.

Try fixing that, restarting your server, and I think you should be good to go.

**Comment by adejeffchen** [comment]
OMG. Typical newbie copy paste mistake. 

After fixing the Directory, restart, it works now. 

Thank you so much.
