### ISSUE TITLE
Not seeing changes with CSS

### ISSUE THREAD

**Issue by kristysunnyd** [susanBuck/e15-spring21#22]
**Environment**
Local server

**What operating system are you using?**
Mac

**Describe the problem**
For some reason, my CSS is not being reflected on the page. The CSS file is located under the **resources** folder and this is the link I've set up under `<head>`:

`<link href='/css/style.css' rel='stylesheet'>`

**Steps taken**
I've tried deleting the link in the parent view and putting it in the child view. Am I doing something wrong? Or is it some permissions I haven't changed?

**Comment by kerynegan** [comment]
@kristysunnyd It looks like you named your CSS file '/css/**app**.css', not '/css/**style**.css', at least in your current github p2 folder [here](https://github.com/kristysunnyd/e15/tree/main/p2/resources/css). Or are you referring to a different style.css file that isn't in your p2 repo right now?

**Comment by kristysunnyd** [comment]
Hi @kerynegan, Yes, I tried adding a new file name style.css into the CSS folder. I just haven't pushed the new changes into Github yet.. 😅

**Comment by susanBuck** [comment]
Hi @kristysunnyd -

Any CSS files you put in _/resources/css_ are not going to be accessible by the browser. The role of the _/resources/css_ directory is to hold pre-built files that a build system would read from and ultimately write to _/public/css_.

**Because we're not using any CSS pre-processing/build systems, you want to just put your CSS files directly in _/public/css_.**

Recall that the _public_ directory is the only directory the browser will have access to, so that's where we put client-side assets such as CSS and JS files or images.

If after you reorganize things you're still not seeing your styles applied, let us know. : )

**Comment by kristysunnyd** [comment]
Hi @susanBuck, 

I've moved my CSS file into the Public directory under _public/css_ and changed the link to this:
`<link href='/public/css/style.css' rel='stylesheet'>` 

But it still doesn't seem to be reflecting the styles... 😢  Have I entered the wrong path for the link? 

Thank you for the help! 🙏

**Comment by susanBuck** [comment]
You can omit _/public_ from the path - that's implied since your document root is already pointing to _public/_.

Try this:

```html
<link href='/css/style.css' rel='stylesheet'>
```

I think that should do the trick :)

**Comment by kristysunnyd** [comment]
Yes, it works now. 😄 I have definitely learned from this. Thank you very much!!

**Comment by susanBuck** [comment]
Glad it's working - you're welcome! :-)
