### ISSUE TITLE
Okay to rebuild repository now ? 

### ISSUE THREAD

**Issue by cgiansante** [susanBuck/e15-spring21#25]
**Environment**
Local server & GitHub

**What operating system are you using?**
Mac

**Describe the problem**
I had some difficultly publishing my last project to production and did not get it sorted out until the last minute. So now I am getting my environment set up for project 3. I am familiar with AWS and have been successful with getting Laravel set up there, [here is an example](http://e15p3.giansante.me) of my project 2 from an EC2 image.

Now, I am having issues pushing changes from my local environment to my e15 git repository. After doing an add -all then a commit, I get a message, 'nothing to commit, working tree clean'. The folders are very different at this point and  I'm not sure where I went wrong here (something to do with branches, I think).  I want to start my GitHub e15 repository over but I don't want to interfere with grading so I'm wondering if it is okay to start my e15 repository over now or if I should wait ? Is there a way to build my e15 repository with the content on my local e15 ? 

I am also interested in knowing if you see any specific challenges with AWS and the features we will be developing in project 3? To facilitate the discussion, I would like to share my learnings and the process I used for this. Is this forum an appropriate place for this discussion or is another place better ? 

Thank you,
Curtis

**Comment by susanBuck** [comment]
Hi @cgiansante -

Yes, you could re-build your e15 repository on Github from what you have locally. 

There are different ways of doing this. Because I don't know what exactly is going on with your e15 repository locally, a "fresh start" might be the best option.

Here's how I would go about doing that.

First, delete your Github e15 repository at https://github.com/cgiansante/e15.

Then, re-crete a new repository on Github (named *e15* again). You will now have a brand new and empty repository on Github.

Next, locally, within your e15 repository, delete the directory `.git` - this will effectively "de-git" your directory, making it a regular directory. You can confirm this is done correctly by running `git status` within your e15 directory, and it should give you the following feedback:

```
fatal: Not a git repository (or any of the parent directories): .git
```

Once this is done, run `git init` to re-initialize it as a new git repository.

Now stage and commit all the files:

```
git add --all
git commit -m "First commit on rebuilt repo"
```

Finally, you need to connect the local e15 repository and the Github.com e15 repository, pushing the above changes. Do that with the following commands:

```
git remote add origin git@github.cgiansante/e15.git
git branch -M main
git push -u origin main
```

At this point your local e15 and Github e15 should be perfectly in sync. You should only have one branch called *main*. You should be able to make changes locally, stage, commit, and push them to Github.


## RE: Using a AWS server
Because you've already successfully launched a Laravel application on your AWS server (http://e15p3.giansante.me/), I don't think you should run into any problems with it for Project 3, but I can't say for 100% sure. 

The only thing that will be unique about Project 3 vs. Project 2 is that we'll be setting up a database - so as long as you can operate MySQL on the AWS server you set up, it should be fine. But again, I can't say for 100% sure. : )

**Comment by cgiansante** [comment]
Thank you! I rebuilt my repository and successfully deployed a change from my local to my production. 

I put some [notes together](https://github.com/susanBuck/e15-spring21/issues/26) on how to configure an EC2 for Laravel if anyone is interested. I will close that issue as it is intended more for reference and discussion.
