### ISSUE TITLE
Importing csv into database - issues with mapping

### ISSUE THREAD

**Issue by sneadthaman** [susanBuck/e15-spring21#30]
**Repository URL**
https://github.com/sneadthaman/e15/tree/main/p3

**Describe the problem**
I've been wanting to make a business dashboard for awhile and I think it may fit our Project 3 perfectly, however, I am attempting to import a csv file and am met with this error:
![image](https://user-images.githubusercontent.com/30006142/115286086-a982a600-a11c-11eb-9a17-84acae9de3ff.png)

It's pretty clear to me that there is a mapping issue going on , so I attempted to import the csv file manually in the phpMyAdmin and I can see a bit more of the problem:
![image](https://user-images.githubusercontent.com/30006142/115286279-e353ac80-a11c-11eb-90ed-7504d545dfd0.png)

The ID number, which should begin at 1 and increment automatically, is actually the first field of the csv - Salesperson Code (185) -and the rest of the fields are hit or miss (some are mapping and others aren't).

This was the article I found online that "helped" get me to this point: https://justlaravel.com/import-csv-data-store-database/?utm_source=learninglaravel.net

The author of the article creates a Model class called 'Csvdata' which I've renamed to 'Customer' to provide consistency considering my table name is 'customers'. That seems to be correct...

Any ideas on what I am doing wrong regarding the mapping of the csv file to my customers table?

**To Reproduce**
1. Clone project and run locally

**Comment by susanBuck** [comment]
Cloning locally now to reproduce. Will follow-up shortly with any insights.

**Comment by susanBuck** [comment]
Hi @sneadthaman -

I went through your code and identified some problem spots, summarized below.

FYI/Tip: I started by reducing the amount of data in your CSV file to 5 rows to get everything working. This is useful because it lets the page load quicker when developing, and it's easier to distinguish between problems in the code and problems in the data. Once you get it working with 5 rows (or some smaller subset), then you can add back the rest of the data.


## Problem 1
The heading row (`Salesperson Code,Salesperson Name,Customer Category, etc...`) was being interpreted as data and causing problems. To get around this I removed that row from the CSV file.

## Problem 2
Some of your fields like `salesperson_code`, `salesperson_name`, and `cust_category` are not being supplied values, and as a result it was throwing an error when trying to add new rows.

To address, make sure these fields are nullable:

```php
$table->integer('salesperson_code')->nullable(); 
$table->string('salesperson_name')->nullable();
$table->integer('cust_category')->nullable(); 
```

## Problem 3
It was then failing when trying to enter values like ` $34,726.96 ` into fields expecting float values. To address this, strip the `$`, `,` and space characters out of your float values. For example:

```php
$csv_data->sales_ytd = str_replace(['$', ',', ' '], '', $data[11]);
```

## Problem 4
For your float values, I was also seeing errors like:

> Data truncated for column 'gpdollars_ytd'

This happened because float fields default to (8,2) meaning it can support 8 digits and 2 decimal points. 

Here's a screenshot of this shown in the structure tab of phpMyAdmin:
![image](https://user-images.githubusercontent.com/237711/115294796-0be0a400-a127-11eb-976b-235667390581.png)

Some of your numbers were greater than 8 digits. To address, expand on the default range when defining floats in your migrations. For example:

```php
$table->float('sales_ytd', 15, 2)->nullable();
```

## Problem 5
There was incorrect indexing for some of the data. For example, for _cust_number_, it was pulling from index 6, but it's actually at index 3.

Here are all the ones that needed to be fixed:
```php
$csv_data->cust_number = $data[3]; # Previously: 6
$csv_data->cust_name = $data[1]; # Previously: 7
$csv_data->cust_city = $data[5]; # Previously: 8
$csv_data->cust_state = $data[6]; # Previously 9
$csv_data->cust_zip = $data[7]; # Previously 10
$csv_data->sales_ytd = str_replace(['$', ',', ' '], '', $data[8]); # Previously: 11
$csv_data->gpdollars_ytd = str_replace(['$', ',', ' '], '', $data[9]); # Previously: 12
$csv_data->gppercent_ytd = str_replace(['$', ',', ' '], '', $data[10]); # Previously: 13
```

To help make sure I had the right index, [I loaded the CSV into a spreadsheet so I could label each column...](https://docs.google.com/spreadsheets/d/18juv9Ld6tai2cf6PWeOfFfXAfDArq4ncavPJcu6xovk/edit#gid=1331304430)


## Problem 6
Once all of the data problems were cleared up, it was failing when passing data to the view. To fix, amend your return statement in populateCustomerList from:

```php
// This won't actually return the data
return $finalData = $csv_data::all();
```

To:

```php
// This will
return $csv_data::all();
```

Also, amend the line that's returning with the view with data from:

```php
// The `with` method is used to attach data when returning redirects, but not when returning views
return view('welcome')->with($customerList);
```

To:

```php
// This is the correct way to attach data to a view
return view('welcome', ['customer_list' => $customerList]);
```

---

With the above changes in place, I was able to get your database populated and your dashboard to load. Let me know if you have any follow-up questions about any of the above.

**Comment by sneadthaman** [comment]
Wow - thank you for the thorough response! It seems I had more than just a mapping issue. Much appreciated

**Comment by zrashidharvard2020** [comment]
This was also helpful to me . I was also working with the CSV import. Thank you .

**Comment by susanBuck** [comment]
@sneadthaman , @zrashidharvard2020 - Glad it was helpful! Working with existing data can be fun and frustrating all at the same time. :-)
