### ISSUE TITLE
Error message when running composer require --dev laravel/dusk - "Your requirements could not be resolved to an installable set of packages."

### ISSUE THREAD

**Issue by karnaout** [susanBuck/e15-spring21#32]
**Repository URL**
https://github.com/karnaout/e15/tree/main/p3

**Production URL**
http://e15p3.khaledarnaout.me/

**Describe the problem**
I recently upgraded my macOS Big Sur to version 11.3 and then tried to install dusk but I got this error message:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/dusk[v6.15.0, ..., 6.x-dev] require ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
    - Root composer.json requires laravel/dusk ^6.15 -> satisfiable by laravel/dusk[v6.15.0, 6.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
![image](https://user-images.githubusercontent.com/13064007/116551754-3b7d7200-a8c6-11eb-98a5-f5b623572d3d.png)

It seems to be related to php-zip and where my php.ini file lives. However, I tried to fix this issue in a few different ways but none of them worked. 

- I tried to reinstall php-zip by running this command `sudo apt install php-zip` and got this error message:
![image](https://user-images.githubusercontent.com/13064007/116552532-2228f580-a8c7-11eb-838d-399aabfc270c.png)

- I tried to require a different version of dusk but that didn't work either.

**To Reproduce**
1. Go to /p3
2. in terminal run `composer require --dev laravel/dusk`
4. See the error message 
![image](https://user-images.githubusercontent.com/13064007/116553122-c874fb00-a8c7-11eb-876c-e0ff95cc5697.png)

**Additional context**

- running  `php --ini` returns:
![image](https://user-images.githubusercontent.com/13064007/116552871-851a8c80-a8c7-11eb-988c-774dd14e66b3.png)

- running `which php` returns:
![image](https://user-images.githubusercontent.com/13064007/116552920-95cb0280-a8c7-11eb-94c6-ae4e2416c663.png)

**Comment by susanBuck** [comment]
It looks like your system is using the default install of PHP that comes on Macs. You'll want to update this so it's using the XAMPP install of PHP which has all the extensions we need. 

This was something that came up earlier when we first set up Composer: https://hesweb.dev/e15/notes/php/composer-mac

Instructions for getting your system to recognize a different install of PHP can be found here: https://hesweb.dev/e15/notes/command-line/path

Let me know if you have any issues as you're going through those steps.

**Comment by kerynegan** [comment]
In case it's helpful, I had a fair amount of trouble with updating my PHP path permanently to XAMPP in my initial installation with Big Sur running in zsh instead of bash. Once I changed my default Terminal to bash, I was able to update my path and things went a lot more smoothly. 

EDIT: If I remember correctly, I had to change my default and [upgrade ](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba)my bash

**Comment by karnaout** [comment]
> It looks like your system is using the default install of PHP that comes on Macs. You'll want to update this so it's using the XAMPP install of PHP which has all the extensions we need.
> 
> This was something that came up earlier when we first set up Composer: https://hesweb.dev/e15/notes/php/composer-mac
> 
> Instructions for getting your system to recognize a different install of PHP can be found here: https://hesweb.dev/e15/notes/command-line/path
> 
> Let me know if you have any issues as you're going through those steps.

Thank you @susanBuck for your reply. I'll give it a try.

**Comment by karnaout** [comment]
> In case it's helpful, I had a fair amount of trouble with updating my PHP path permanently to XAMPP in my initial installation with Big Sur running in zsh instead of bash. Once I changed my default Terminal to bash, I was able to update my path and things went a lot more smoothly.
> 
> EDIT: If I remember correctly, I had to change my default and [upgrade ](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba)my bash

Thanks for the tip @kerynegan!

**Comment by karnaout** [comment]
@susanBuck Thanks for your help. Changing php install on my make fixed my problem. Although I want to mentioned that for some reasons inserting `PATH=/Applications/XAMPP/xamppfiles/bin:$PATH` in my `.bash_profile` per the instructions in [PATH variable](PATH=/Applications/XAMPP/xamppfiles/bin:$PATH) didn't resolve my issue. However, other [resources on the internet](https://gist.github.com/djandyr/c04950a1375e96814316) suggested that I use `export PATH=/Applications/XAMPP/bin:$PATH` and then `source ~/.bash_profile` which did indeed fix my problem and changed the PHP install to the XAMPP one.

**Comment by susanBuck** [comment]
Thanks for the follow-up, @karnaout - 

Note that `export PATH=/Applications/XAMPP/bin:$PATH` will add a new path to your PATH variable, but it will only be temporary - the next time you close/reopen terminal, the changes will be gone.

To confirm/test this, I did the following:

1. Ran `export PATH=/test:$PATH` to add a path, `/test`
2. Ran `echo $PATH` to see my path variables. Confirmed I saw `/test` at the start of the list.
3. Closed and re-opened terminal.
4. Ran `echo $PATH` again, and confirmed `/test` was no longer on the list.

When you followed my notes for updating `~/.bash_profile`, is it possible you missed the step on restarting Terminal? That step is necessary to get it to recognize changes you made to `~/.bash_profile` and would explain why the steps in the notes didn't work.

However, you did later run `source ~/.bash_profile` which is another way you can get Terminal to recognize changes to `~/.bash_profile`.  (Side note: `source ~/.bash_profile` is not actually needed for the "export PATH..." solution to work.)

Here's what I suspect happened...
1. You followed my notes but missed the step of getting Terminal to recognize the changes, so it didn't work
2. You found the "export PATH..." solution which temporarily fixed the problem. At the same time you also ran `source ~/.bash_profile` which would have fixed why my steps didn't work.
3. The next time you restart Terminal it will still work - not because of the "export PATH..." solution, but because it was now successfully reading the updated paths from your `~/.bash_profile`.


Regardless, the important thing is it's working now. :-)
