### ISSUE TITLE
Relationships: Many to Many with the same table

### ISSUE THREAD

**Issue by adejeffchen** [susanBuck/e15-spring21#34]
If I have a many to many relationship with the same table, what is the recommended pivot table name? For example, a user can relate to many other users. 

According to lecture note: 
> The convention for naming our pivot tables is to use the singular version of the name of the two tables you’re joining, separated with an underscore, in alphabetical order.

Should the pivot table name be user_user? or I can just called it related_user?

Thanks.

**Comment by susanBuck** [comment]
I would not use `related_user` because it's mimicking the pivot table conventions, but does not actually represent two tables connecting, which could be confusing. 

You could call it `user_user`, yes. This way it's clear when looking at the table name what it's connecting.

If that feels awkward, you could name the table after the relationship it represents. E.g. if it was a social network connecting users maybe the table name is `friendships`.

If you do a "custom" table name like this, here are the instructions on how to inform Eloquent of this custom name:

![image](https://user-images.githubusercontent.com/237711/117545391-96644700-aff3-11eb-8ea7-5f493bceaef2.png)

https://laravel.com/docs/8.x/eloquent-relationships#many-to-many-model-structure

**Comment by adejeffchen** [comment]
Thank you! This helps.
